### ISSUE TITLE
Differences between alpha and beta models

### ISSUE THREAD

**Issue by liutianlin0121** [huggingface/alignment-handbook#12]
Hi!

I am wondering if there is an official documentation of differences between zephyr-7b-alpha and zephyr-7b-beta. 

According to [this blog](https://gathnex.medium.com/zephyr-7b-beats-chatgpt-huggingface-open-challenge-to-openai-bba2fceecd9c)

> Zephyr beta trains for more DPO epochs (than Zephyr alpha) leading to better chat results!

According to [this linkedin post](https://www.linkedin.com/posts/maxime-labonne_zephyr-beta-7b-llm-outperforms-chatgpt-activity-7123617839776768000--F5v/?trk=public_profile_like_view)

> Compared to Zephyr-Alpha, they filtered the data to get rid of issues related to incorrect casing and weird starts for some answers.

The above sources are from 3rd parties. I'm curious if there's an official reference for these differences. The [Zephyr paper](https://arxiv.org/pdf/2310.16944.pdf) doesn't appear to cover them. Thanks a lot!

Tianlin

**Comment by lewtun** [comment]
Hi @liutianlin0121 thanks for your question! We're still working on the guides for the handbook where we'll explain these distinctions in detail, but the tl;dr is that they differ in two main ways:

* The SFT policy of `zephyr-7b-alpha` was trained on a larger, less filtered version of UltraChat (I think we can open source it soon). We later found that this subset had a lot of grammatical errors which were fixed for `zephy-7b-beta`
* `zephyr-7b-alpha` was trained for 1 DPO epoch, while `zephyr-7b-beta` was trained for 3. 

Hope that helps!

**Comment by liutianlin0121** [comment]
I see! Thanks so much for your help!
