### ISSUE TITLE
Missing  config_qlora.yaml 

### ISSUE THREAD

**Issue by IsraelAbebe** [huggingface/alignment-handbook#136]
Should there be config_qlora.yaml in  zephyr-7b-gemma/sft/

based on this [README](https://github.com/huggingface/alignment-handbook/tree/main/scripts)  or am i missing something?

**Comment by jaywongs** [comment]
same confusion here.

**Comment by IsraelAbebe** [comment]
@jaywongs you can copy and create from the others, I tried it.
