### ISSUE TITLE
TypeError: Trainer.create_model_card() got an unexpected keyword argument 'revision'

### ISSUE THREAD

**Issue by tanliboy** [huggingface/alignment-handbook#185]
When fine-tuning using the SFTTrainer, it failed in the last step in pushing the model to the hub.

The exception is as below:
```
    trainer.push_to_hub(revision=training_args.hub_model_revision, **kwargs)
  File "/opt/conda/envs/handbook/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 475, in push_to_hub
    return super().push_to_hub(commit_message=commit_message, blocking=blocking, **kwargs)
  File "/opt/conda/envs/handbook/lib/python3.10/site-packages/transformers/trainer.py", line 4345, in push_to_hub
    self.create_model_card(model_name=model_name, **kwargs)
TypeError: Trainer.create_model_card() got an unexpected keyword argument 'revision'
```

I am on the latest versions of transformers (4.43.3) and trl (0.9.6). This problem seems to be related to the PR (https://github.com/huggingface/alignment-handbook/pull/182) yesterday. Or did I miss something?

Cc @kashif

**Comment by kashif** [comment]
oh snap! ok let me see i think the create_model_card should not have that `kwargs` fixing!

**Comment by tanliboy** [comment]
Thank you, @kashif !
