### ISSUE TITLE
Push to hub does not work

### ISSUE THREAD

**Issue by DRXD1000** [huggingface/alignment-handbook#198]
Hey, i am training with your script on multiple gpus using accelerate. but when it comes to push to hub the process does not finish and nothing gets uploaded. 

What could be the problem here ? 

An exisiting repo is given and i use a read/write authentication token

'''

    trainer.train()

    # trainer.evaluate()

    if trainer.accelerator.is_main_process:
        tokenizer.truncation_side = "right"
        trainer.model.config.use_cache = True
        trainer.save_model(f"{run_name}/")

    logger.info("Pushing to hub...")

    trainer.push_to_hub()

**Comment by DRXD1000** [comment]
The script previously looked like:


    if accelerator.is_main_process:
        kwargs = {
            "finetuned_from": model_args.model_name_or_path,
            "dataset": list(data_args.dataset_mixer.keys()),
            "dataset_tags": list(data_args.dataset_mixer.keys()),
            "tags": ["alignment-handbook"],
        }
        dpo_trainer.create_model_card(**kwargs)
        # Restore k,v cache for fast inference
        dpo_trainer.model.config.use_cache = True
        dpo_trainer.model.config.save_pretrained(training_args.output_dir)
        if training_args.push_to_hub is True:
            dpo_trainer.push_to_hub()

    # Ensure we don't timeout on model save / push to Hub
    logger.info("*** Waiting for all processes to finish ***")
    accelerator.wait_for_everyone()

should we mabey change the ending of the scripts now to 

if trainer.accelerator.is_main_process:
    if training_args.push_to_hub is True:
        logger.info("Pushing to hub...")
        trainer.push_to_hub(**kwargs)

**Comment by lewtun** [comment]
Hello @DRXD1000 thanks for raising this issue! It looks like a regression indeed - can you share a minimal example using some small models that I can test with please?

**Comment by DRXD1000** [comment]
Hi @lewtun , I'm really sorry for the inconvenience. The problem was, as so often, in front of the screen. I put the saving of the model in the if statement, which of course doesn't work with a sharded model. I moved this line of code forward (as it is in the the current version) and now everything works fine. Sorry again :)

Thank you for your quick reply and your great work on Zephyr. This work was the main inspiration for my first own model earlier this year. 

Have a great weekend. 🤗

Greetings Matthias

**Comment by lewtun** [comment]
Glad to hear it is working now!
