### ISSUE TITLE
Running on single RTX4090

### ISSUE THREAD

**Issue by jasonwtli** [huggingface/alignment-handbook#23]
Hi,

Followed the install.  Tried to run in shell # Step 1 - SFT. for single gpu as per instructions. i.e --num_processes=1 

Kicked up the below error. Is alignment module something  we need to seperately pip install?

'''
from alignment import (
ModuleNotFoundError: No module named 'alignment'

'''

Thanks in advance!  Jason.

**Comment by edbeeching** [comment]
Yes, please follow the installation instructions [here](https://github.com/huggingface/alignment-handbook#installation-instructions). I will close the issue but let us know if you have further difficulties.

**Comment by jasonwtli** [comment]
Tks Ed. Followed exactly the install. It still looking for missing module called "alignment"?

INFO:root:Using nproc_per_node=1.

Traceback (most recent call last):
  File "/home/deeplearner/mlops_development/alignment-handbook/scripts/run_sft.py", line 30, in <module>
    from alignment import (
ModuleNotFoundError: No module named 'alignment'
