### ISSUE TITLE
SFT checkpoint of zephyr-7b

### ISSUE THREAD

**Issue by liutianlin0121** [huggingface/alignment-handbook#5]
Hi!

Thanks for releasing the Zephyr-7b-alpha model! I am wondering if it is possible to access the SFT checkpoint of Zephyr-7b (the model prior to DPO training).  

As I understand, the SFT training of Zephyr-7b was done based on [this script](https://gist.github.com/lewtun/b9d46e00292d9ecdd6fd9628d53c2814). This is very useful! Since the SFT training script is open-source, could you also release a SFT model checkpoint? Having access to the SFT checkpoint would help us investigate the impact of DPO without requiring significant GPU resources.

Thanks for your consideration!
Tianlin

**Comment by liutianlin0121** [comment]
> Hi Tianlin! Yes we plan to release the SFT checkpoint quite soon and I'll report back here when it's available 🤗 

Awesome, thanks! 🤗

**Comment by lewtun** [comment]
Hi @liutianlin0121 we've now released the two SFT checkpoints behind `zephyr-7b-alpha` and `zephyr-7b-beta` and you can find them in this collection under `mistral-7b-sft-{alpha,beta}`: https://huggingface.co/collections/HuggingFaceH4/zephyr-7b-6538c6d6d5ddd1cbb1744a66

**Comment by liutianlin0121** [comment]
Many thanks!! 🤗
