### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by renjie130** [huggingface/alignment-handbook#6]
Could you please release the releated codes?

**Comment by lewtun** [comment]
Coming soon 🤗 !

**Comment by fblgit** [comment]
Same here, placeholder everywhere.. look like got bogus content..

**Comment by sooftware** [comment]
@lewtun Can you tell me when it will be released?

**Comment by lewtun** [comment]
Very soon 😁!

**Comment by zhangmozhe** [comment]
Waiting

**Comment by lewtun** [comment]
Sneak peek :) https://github.com/huggingface/alignment-handbook/pull/11
