### ISSUE TITLE
Chat template is being overwritten when the Tokenizer has a `default_chat_template`.

### ISSUE THREAD

**Issue by nathan-az** [huggingface/alignment-handbook#84]
`PreTrainedTokenizerBase.apply_chat_template` contains the following logic:

```py
        if chat_template is None:
            if self.chat_template is not None:
                chat_template = self.chat_template
            else:
                chat_template = self.default_chat_template
```

`get_tokenizer` currently does not respect `default_chat_template` and overwrites `chat_template` without checking if the class has a default. In my use case, I noticed that the CodeLlamaTokenizer is implemented using `default_chat_template`, which was being ignored.

Attempt to fix https://github.com/huggingface/alignment-handbook/pull/83

**Comment by lewtun** [comment]
Closed by #83
