### ISSUE TITLE
How can I config `loss_type`?

### ISSUE THREAD

**Issue by hahuyhoang411** [huggingface/alignment-handbook#87]
I want to change the **loss_type** into KTO or something else to test but I can't. Please show me the way. Thank you.

**Comment by lewtun** [comment]
Hi @hahuyhoang411 ! This can be done by passing `loss_type` to the `DPOTrainer` and will be fixed in the linked PR above

**Comment by hahuyhoang411** [comment]
Great news. Thanks.

Anw do you want also to implement Unsloth? I saw TRL support Unsloth which could reduce the memory usage.
