### ISSUE TITLE
huggingface_hub version

### ISSUE THREAD

**Issue by Harry-mic** [huggingface/alignment-handbook#94]
Hello! I encounter an issue when pip the repo.

After I install the requirements and try :
`ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/multi_gpu.yaml --num_processes=1 scripts/run_dpo.py recipes/accelerate_configs/deepspeed_zero3.yaml scripts/run_dpo.py recipes/zephyr-7b-beta/dpo/config_lora.yaml`, 
it came an error:
`cannot import name 'HF_HOME' from 'huggingface_hub.constants'`,
Could you please give a feasible version of huggingface_hub, tokenizers and transformers you use? Mine is huggingface_hub==0.17.3, tokenizers==0.14.0,transformers ==4.35.0

**Comment by bugface** [comment]
HF_HOME is env variable, you need to define in run script like
```bash
# bash
export HF_HOME="somewhere on you local"
```
or use python
```python
import os

os.environ["HF_HOME"] = "somewhere on you local"
```

**Comment by bugface** [comment]
https://github.com/huggingface/huggingface_hub/releases/tag/v0.19.2

`huggingface_hub>=0.19.2` should work.
